"""lead_name

Revision ID: f33389aea5cc
Revises: 0c495853ab88
Create Date: 2025-04-03 11:18:01.739280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33389aea5cc'
down_revision = '0c495853ab88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'name')
    # ### end Alembic commands ###
