"""user2

Revision ID: 3097837489fc
Revises: 0aa8ba39ca2c
Create Date: 2025-04-03 08:29:17.595967

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3097837489fc"
down_revision = "0aa8ba39ca2c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user", ["email"])
    op.create_unique_constraint(None, "user", ["phone"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    # ### end Alembic commands ###
