"""user

Revision ID: 0aa8ba39ca2c
Revises: 93a8e770c719
Create Date: 2025-04-03 08:27:57.293958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa8ba39ca2c'
down_revision = '93a8e770c719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_phone_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_phone_key', 'user', ['phone'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
